---
title: "PSYC 30550"
author: "Sooyoun"
short_title: "Ses-infer project Rmd"
---

```{r study description, echo=TRUE}

Survey participants will read one of the two personal narratives signaling different social classes. They will make inferences about the narrator, including the narrator's education level, relative social class, competence level, and intelligence level. They will also indicate their willingness to hire the narrator from an employer's perspective, and their demographic info.

The study will explore,
1. Whether participants accurately guess the narrator's social class.
2. Whether the upper-class narrator is inferred to be more competent and intelligent than the lower-class narrator.
3. Whether such inferences about the narrator influence participants' willingness to hire the narrator.
4. Whether participants' social class affect these tendencies.

```

# HW 9: Data prep

```{r data preparation, echo=TRUE}

library(readxl)
library(dplyr)
library(writexl)
library(tidyverse)

# Read data
dataset <- read_xlsx("dataset.xlsx")

# Tidiness check
str(dataset)

# Data wrangling
data_prep <- dataset %>%
  select(type, gender, age, edu, class, hire, a_inc, a_edu, a_class, comp, intel) %>%   # select columns
  filter(age > 35) %>%    # only include participants above age 35
  mutate(across(c(type, gender), factor)) %>%
  mutate(type = case_when(
    type == "1" ~ "upper-class",
    type == "2" ~ "lower-class",
    TRUE ~ type  )) %>%   # name two types of stimuli
  mutate(gender = case_when(
    gender == "1" ~ "male",
    gender == "2" ~ "female",
    TRUE ~ gender  )) %>%   # name two types of gender
  mutate(across(c(type, gender), factor)) %>%   # type and gender are factor variables
  mutate(social_class = type, evaluator_gender = gender, evaluator_age = age, evaluator_edu = edu,
         evaluator_class = class, hiring_pref = hire, perceived_inc = a_inc, perceived_edu = a_edu,
         perceived_class = a_class, perceived_comp = comp, perceived_intel = intel) %>%   # change names
  select(social_class, perceived_inc, perceived_edu, perceived_class, perceived_comp, perceived_intel, hiring_pref,
         evaluator_gender, evaluator_age, evaluator_edu, evaluator_class)   # final column selection

# Data description: perceived_(  ) refers to participants' indicated perception of the narrator. evaluator_(  ) refers to participants' reported demographic info.

# Tidiness check
str(data_prep)

# Export data
write_xlsx(data_prep, "data_prep.xlsx")

```

# HW 10: Plots

```{r plot plan, echo=TRUE}

1. Group Bar Chart: Perceived competence and intelligence by narrator's social class

**Data Requirements**:
  - social_class (categorical): the type of narrative the participant read (upper-class, lower-class)
  - perceived_comp (numerical, continuous): perceived competence of the narrator
  - perceived_intel (numerical, continuous): perceived intelligence of the narrator
**Plot Elements**:
  - X-axis: social_class
  - Y-axis: average scores of perceived_comp and perceived_intel
  - Two sets of bars for each social_class (different colors)

2. Line Chart: Participant's willingness to hire the narrator based on own social class

**Data Requirements**:
  - evaluator_class (numerical, continuous): self-reported subjective social class of participants
  - hiring_pref (numerical, continuous): participants’ willingness to hire the narrator
**Plot Elements**:
  - X-axis: evaluator_class (group into meaningful categories?)
  - Y-axis: average hiring_pref
  - Create separate lines for each social_class (different colors)

# These plots will visually summarize (1) the impact of perceived social class on narrator evaluation and (2) the influence of participants' own social class on these patterns.

```

```{r HW 11 plot code, echo=TRUE}

# HW 11

library(ggplot2)
library(dplyr)

starwars_data <- read.csv('sw-wrangled.csv')

# Histogram of the height_cm column
ggplot(starwars_data, aes(x = height_cm)) +
  geom_histogram(binwidth = 10, fill = "grey", color = "black") +
  labs(x = "height_cm", y = "count")

# Histogram of hair color sorted
starwars_data <- starwars_data %>% 
  filter(!is.na(hair)) 
starwars_data %>%
  count(hair) %>% 
  mutate(sorted_hair = reorder(hair, n)) %>%
  ggplot(aes(x = sorted_hair, y = n)) +
  geom_bar(stat = "identity", fill = "grey", color = "black") +
  labs(x = "Hair Color", y = "Count")

# Scatter plot of mass vs. height_in
ggplot(starwars_data, aes(x = height_in, y = mass)) +
  geom_point(shape = 17) +  # shape 17 is a filled triangle
  labs(x = "height_in", y = "mass", ylim = c(0,50))

## The outlier (1358) ? How should I manage it?
## Can “pretty up” my plots by adding codes like theme_minimal(), grouping by color, etc.

```

```{r HW 12 plot code, echo = TRUE}

library(dplyr)
library(ggplot2)

starwars_data <- read.csv('sw-wrangled.csv')
data <- starwars_data %>%
  filter(mass != 1358) ## example plots don't seem to have this value so I excluded...

# Plot 1
plot <- ggplot(data, aes(x = hair, y = mass, fill = hair)) +
  geom_boxplot(alpha=0.3) +
  theme(legend.position="none") +
  labs(x = "Hair color (s)", y = "Mass (kg)") +
  theme_minimal()
print(plot)

# Plot 2

data$brown_hair_category <- ifelse(data$hair == "brown", "Has brown hair", "No brown hair")
plot <- ggplot(data, aes(x = mass, y = height_in)) +
  geom_point() + 
  geom_smooth(method = "lm", color = "blue", fill = "blue", alpha = 0.2) +
  facet_wrap(~brown_hair_category) +
  labs(title = "Mass vs. height by brown-hair-havingness",
       subtitle = "A critically important analysis",
       x = "mass", y = "height_in") +
       theme_minimal()
print(plot)

# Plot 3

species_gender_count <- data %>%
  group_by(species_first_letter = substr(species, 1, 1), gender) %>%
  summarise(count = n(), .groups = 'drop')
plot <- ggplot(species_gender_count, aes(x = species_first_letter, y = count, fill = gender)) +
  geom_bar(stat = 'identity', position = 'stack') +
  coord_flip() +
  labs(x = "species first letter", y = "count", title = "A clear male human bias") +
  theme(plot.title = element_text(hjust = 1, size = 8, vjust = 1)) +
  theme(legend.position="bottom") +
  scale_fill_manual(values = c("m" = "cyan3", "f" = "salmon")) +
  theme_minimal()
plot <- plot + 
  theme(plot.title = element_text(hjust = 1, vjust = 1, size = 10, face = "plain"),
        plot.title.position = "plot")
print(plot)

# Adding code for HW 10

# Participant's willingness to hire the narrator based on own social class
# Group evaluator_class
data$evaluator_class_grouped <- cut(data$evaluator_class, breaks=quantile(data$evaluator_class, probs=0:5/5), include.lowest=TRUE, labels=FALSE)

# Average hiring_pref for each group of evaluator_class
avg_hiring_pref <- data %>%
  group_by(evaluator_class_grouped, social_class) %>%
  summarise(average_hiring_pref = mean(hiring_pref, na.rm = TRUE), .groups = 'drop')

# Diff clors for two social class groups
colors <- c("lower-class" = "lightslateblue", "upper-class" = "hotpink2")

# Line chart with separate lines for each 'social_class'
ggplot(avg_hiring_pref, aes(x = evaluator_class_grouped, y = average_hiring_pref, group = social_class, color = social_class)) +
  geom_line() +
  geom_point() +
  labs(x = "Evaluator social class", y = "Average hiring preference") +
  scale_x_continuous(breaks = unique(avg_hiring_pref$evaluator_class_grouped)) +
  scale_color_manual(values = colors)

# Tuning up HW 11 plot

starwars_data <- starwars_data %>% 
  filter(!is.na(hair)) 
starwars_data %>%
  count(hair) %>% 
  mutate(sorted_hair = reorder(hair, n)) %>%
  ggplot(aes(x = sorted_hair, y = n, fill = hair)) +
  geom_bar(stat = "identity") +
  labs(x = "Hair Color", y = "Count") +
  scale_fill_brewer(palette = "Set3") +
  theme_minimal(base_size = 14)

```

